### ISSUE TITLE
Don't include getGeneratedCMSFields when a subclass has no own fields or relations

### ISSUE THREAD

**Issue by wernerkrauss** [unclecheese/SilverSmith#31]
I stumbled across a problem with my Gallery implementation:

```
PageTypes:
  ImageGalleryPage:
    Fields: {}
    Components:
      ImageGalleryAlbum:
        Type: many
        Interface:
          Type: grid
        Tab: GalleryAlbum
  ProjektPage:
    Parent: ImageGalleryPage
    Fields: {}

Components: 
  ImageGalleryAlbum:
    Tab: GalleryAlbum
    Fields:
      Folder: {CMSField: RelationDropdown, Map: Folder}
      AlbumName: {CMSField: Textarea}
      Description: {CMSField: Textarea, DBField: Varchar(255)}
      CoverImage: {CMSField: Image}
```

When trying to add an Album to the ProjektPage it doesn't work. Commenting out the whole getGeneratedCMSFields() method in ProjektPage made it working. The error was like:

```
Uncaught LogicException: byID can't be called on an UnsavedRelationList
```

After some testing i changed the code in getGeneratedFormFields to:

```
        $parentClassName = get_parent_class($this);
        $parentClass = new $parentClassName;
        $fields = ($parentClass->hasMethod('getGeneratedCMSFields'))
            ? parent::getGeneratedCMSFields()
            : parent::getCMSFields();
```

which seems to work for now in the subclass.

Please have a look at it. Thanks ;)
