### ISSUE TITLE
[IDEA] Place generated files in PHPDoc @package and @subpackage dirs

### ISSUE THREAD

**Issue by anselmdk** [unclecheese/SilverSmith#9]
Just an idea: I think it would be great if you could define `package` and `subpackage` on components and pages in your `project.yml` file.
The idea is for Silversmith then being able to place files in different directories.

Example, `project.yml`:

```
PageTypes:
    MyPage:
        Package: mysite
        Subpackage: pagetypes
    MyBasePage:
        Package: mysite
        Subpackage: basepagetypes
    MyOtherPage: 
        Package: myothermodule
        Subpackage: pagetypes
```

Example, code structure:

```
mysite/code/pagetypes/MyPage.php
mysite/code/basepagetypes/MyPage.php
myothermodule/code/basepagetypes/MyOtherPage.php
```

Furthermore this would allow for automatically generating php doc in the file head.
